update the following contents.
1. add the pymssql module which require the freetds-dev due to the issue
of "_mssql.c:266:22: fatal error: sqlfront.h: No such file or directory"
2. add the maxCheckCount parameter to the executeSpark function to be
used.
3. update the parameters of reqCheckDuration and maxCheckCount to
improve the rest API.